### PR TITLE
update release notes for 2.1.0, add subVI to palette

### PR DESCRIPTION
**Pull request by nate-moehring**
Updated release notes and palette for PRs 39 and 41, improved error reporting.
image

### CODE REVIEW

**Comment by nate-moehring** [comment]
Tested install of newly built package.
image

**Comment by nate-moehring** [comment]
Built package
[jki_lib_json_serialization-2.1.0.40.vip.zip](https://github.com/user-attachments/files/16617988/jki_lib_json_serialization-2.1.0.40.vip.zip)

**Comment by nate-moehring** [comment]
To be clear, I think the ball is in your park to review the built package when you get a chance.

**Comment by jimkring** [comment]
Thanks, Nate! I’ll give it a try this weekend

**Comment by jimkring** [comment]
@nate-moehring looking great!  I am making a few other minor tweaks and I'll just add them to this PR, if that's OK...

**Comment by jimkring** [comment]
1) I moved the utility VIs into subpalette
image

2) Made both error inputs of "Add Source Path if Error" required.
image

3) Made some edits to the VI Description (see above) -- started by explaining when to use this VI and why.

4) renamed `error in (no error)` to simple `error in` (see above), since less is more (and it's a recommendation of dnatt I believe).

**Comment by jimkring** [comment]
5) marked `Get UTC Offset.vi` as `source only` (seems we missed that one)

**Comment by jimkring** [comment]
6) renamed `error in (no error)` to `no error` for public VIs (only a few were affected)

**Comment by jimkring** [comment]
7. Added a new example VI that HTTP GET's some JSON and shows how to use the new error handling util.

image

**Pull request merged**
